# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Program Files\anaconda3\envs\Skripsi\Project_Skripsi\splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplasScreen(object):
    def setupUi(self, SplasScreen):
        SplasScreen.setObjectName("SplasScreen")
        SplasScreen.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SplasScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(160, 210, 500, 200))
        self.main_frame.setStyleSheet("\n"
"border-radius:20px;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.logo_frame = QtWidgets.QFrame(self.main_frame)
        self.logo_frame.setGeometry(QtCore.QRect(40, 10, 421, 91))
        self.logo_frame.setStyleSheet("image: url(:/images/images/logo.png);\n"
"background-color:none;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.label_Description = QtWidgets.QLabel(self.main_frame)
        self.label_Description.setGeometry(QtCore.QRect(140, 110, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Description.setFont(font)
        self.label_Description.setStyleSheet("color: rgb(85, 34, 93);")
        self.label_Description.setObjectName("label_Description")
        self.progressBar = QtWidgets.QProgressBar(self.main_frame)
        self.progressBar.setGeometry(QtCore.QRect(40, 150, 421, 7))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(41, 31, 80);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style:none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.518, x2:0.994318, y2:0.54, stop:0 rgba(153, 27, 92, 255), stop:0.875 rgba(105, 30, 124, 255));\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.progressBar.setProperty("value", 22)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        SplasScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplasScreen)
        QtCore.QMetaObject.connectSlotsByName(SplasScreen)

    def retranslateUi(self, SplasScreen):
        _translate = QtCore.QCoreApplication.translate
        SplasScreen.setWindowTitle(_translate("SplasScreen", "Splash Screen"))
        self.label_Description.setText(_translate("SplasScreen", "Welcome to My Application"))
import logo_rc
